### ISSUE TITLE
Add support for compiling without Vulkan SDK

### ISSUE THREAD

**Issue by gwihlidal** [chaoticbob/SPIRV-Reflect#43]
It would be nice to have a mode of compiling SPIRV-Reflect without the need for the Vulkan SDK to be installed (especially if unavailable, like on OS X). It looks like the Vulkan SDK is mainly used for the API that returns descriptor types, etc.. Perhaps in a compilation mode without the Vulkan SDK, the tool would be useful to do general reflection without returning VK specific types.

Currently I get the following cmake error on OS X
`-- The C compiler identification is AppleClang 9.0.0.9000039
-- The CXX compiler identification is AppleClang 9.0.0.9000039
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:15 (message):
  VULKAN_DIR not set, use -DVULKAN_DIR=<path> or set VULKAN_SDK environment
  variable`

This is not a huge issue, but definitely impeding some of my workflows.

Thank you,
Graham

**Comment by cdwfs** [comment]
Graham lad!
Could we just add the SPIRV-Headers repo as a submodule, & fall back on that if the Vulkan SDK isn't available?
~(

**Comment by gwihlidal** [comment]
Works great! Thank you very much
