### ISSUE TITLE
$Global constant buffer is not reflected

### ISSUE THREAD

**Issue by bkaradzic** [chaoticbob/SPIRV-Reflect#47]
When building from HLSL SPRIV-Reflect ignores `$Global` constant buffer.

`glslangValidator -V -D -e main test.frag`

```
uniform float4 u_test0;

cbuffer : register(b0)
{
    float4 u_test1;
};

void main(out float4 fragColor : SV_TARGET0)
{
    fragColor = u_test0 * u_test1;
}
```

`spirv-reflect frag.spv`

will output only descriptor binding for unnamed constant buffer that contains `u_test1`.

**Comment by cdwfs** [comment]
This seems like a compiler issue; if I build your test shader with dxc, spirv-reflect finds both descriptor bindings as expected. With glslc or glslangValidator it behaves as you describe.

**Comment by johnkslang** [comment]
How did dxc know where to bind? That seems a convention, and there are also ways to ask glslang to bind as well. For example, using `--amb`.

Is there an agreed on convention about how to bind $Global?  Is that convention from MS or Google?

**Comment by chaoticbob** [comment]
IIRC, $Globals and $Params, using FXC, are assigned a register using what appears to be the next available register in the #b. 

DXC/SPIR-V follows this same convention but assigns a binding in set 0, I believe. There is an attribute directive that permits you to force a binding number for $Globals. I can't recall what it is off the top of my head. @antiagainst will know.

**Comment by antiagainst** [comment]
+1 to what @chaoticbob said. We are following fxc behavior to use the next available binding in set 0 for the `$Globals` cbuffer. There is no way to manually pick the binding number for it right now. An attribute like `vk::globals_binding` was considered but haven't gotten implemented yet. One reason is not seeing real requests from developers; another reason is not sure about where to attach that attribute to. (Attaching to the entry point seems reasonable, but then we loose the ability to share the info among multiple entry points in the same file unless we attach all of them.)

**Comment by chaoticbob** [comment]
Closing this since it's a compiler behavior and not that of SPIRV-Reflect.
