### ISSUE TITLE
spirv.h inclusion should be more robust

### ISSUE THREAD

**Issue by cdwfs** [chaoticbob/SPIRV-Reflect#54]
Since #44 was merged, `spirv_reflect.h` uses `#include <spirv.h>` to include the SPIRV header. Its CMake file first looks for `spirv.h` in a SPIRV-Headers submodule (falling back on the version in Vulkan SDK if the headers submodule is not found), and configures the project's include paths appropriately for both cases. so that `#include <spirv.h>` works. Unfortunately, this logic must be replicated in projects that embed SPIRV-Reflect, or else the public header's `#include <spirv.h>` is unlikely to work out of the box. This adds an additional obstacle (albeit a mild one) to the integration process.

The core frustrating issue is that the required include path for the SPIRV-Headers submodule isn't compatible with the way most projects include the Vulkan SDK headers. In my experience, most projects add `${VULKAN_SDK}/include` to their include paths, and use `#include <vulkan/vulkan.h>` to access the public Vulkan API. The corresponding include statement for `spirv.h` would therefore be `#include <vulkan/spirv.h>`. However, the "vulkan/" prefix won't work if `spirv.h` is coming from the SPIRV-Headers repo; the full path to the file is:
```
${SPIRV-Headers_SOURCE_DIR}/include/spirv/[1.0? 1.1? 1.2? unified1?]/spirv.h
```
Ideally, including `spirv_reflect.h` should work out-of-the-box for the common case (while still allowing projects to use custom SPIRV headers if desired). But it seems that's only possible if projects have `${VULKAN_SDK}/include/vulkan` in their include paths, instead of (or in addition to) `${VULKAN_SDK}/include`.

**Comment by chaoticbob** [comment]
I ran into this frustration myself when embedding SPIRV-Reflect into a project. The original intention behind SPIRV-Reflect's design was to use the super set of SPIR-V constants, enums, etc. Going back to this, I've made the changes to spirv_reflect.h to use the local copy of unified1/spirv.h. 

This also means copying in unified1/spirv.h and putting it in a non-ambiguous location (I hope). And also removing the SPIRV-Headers module. I checked the history of the repo and the changes aren't frequent enough to cause worry.

Changes are in this commit: https://github.com/chaoticbob/SPIRV-Reflect/commit/5598462f987841f7c1abe9209650ea8d3e727b46.
