### ISSUE TITLE
Specialization constants cannot be used as an array size

### ISSUE THREAD

**Issue by Frizi** [chaoticbob/SPIRV-Reflect#63]
The following shader will currently make SPIRV-Reflect return an error.

```glsl
#version 450

layout (constant_id = 0) const int CONST = 64;
layout(binding = 0) uniform Args {
    vec4 array[CONST];
};

void main() {
    gl_Position = array[0];
    for (int i = 1; i < CONST; i++) {
        gl_Position += array[i];
    }
}
```

I belive that the faulty code is in this line.
https://github.com/chaoticbob/SPIRV-Reflect/blob/8fd9b11dbd217f6b02c9d6d4e364a7f0327b219a/spirv_reflect.c#L1432

The reason is that it tries to read the constant as if it's always a literal. When specialization constants are in play, this is no longer true. The array size constant is `OpSpecConstant` instead of `OpConstant`.

Relevant bits of spirv-dis:
```
             %CONST = OpSpecConstant %int 64
%_arr_v4float_CONST = OpTypeArray %v4float %CONST
              %Args = OpTypeStruct %_arr_v4float_CONST
```

**Comment by chaoticbob** [comment]
@Frizi thanks for this. I'll get it sorted soon!
